"""Generate the paper's result tables directly from the results ledger.

Numbers in a manuscript drift. A table typed by hand is correct on the day it
is typed and silently wrong after the next sweep finishes, and the copy that
goes stale first is usually the one in the abstract. Everything quantitative in
the results section is therefore emitted from ``results.jsonl`` by this script
and pulled in with ``\\input``; rebuilding the paper after new runs land
updates every figure at once, or fails loudly.

Usage::

    python scripts/make_tables.py
    python scripts/make_tables.py --ledger runs/phase0/results.jsonl --epoch 199

Writes ``paper/tables/*.tex``. Configurations with fewer seeds than requested
are marked rather than dropped: a reader should see that an arm is
under-sampled, not silently receive a mean over three runs alongside means over
five.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from awwl.analysis.results import load_results
from awwl.analysis.stats import compare_to_baseline, summarize_groups

# Presentation order and display names. Ordering by hand rather than
# alphabetically keeps the baseline first and the ablations grouped, which is
# how the text walks through them.
ROWS: list[tuple[str, str]] = [
    ("mse", r"MSE \emph{(baseline)}"),
    ("l1", r"$L_1$"),
    ("huber", r"Huber"),
    ("charbonnier", r"Charbonnier"),
    ("snr_weighted", r"SNR-weighted"),
    ("static_wavelet", r"Static wavelet ($p{=}0$)"),
    ("awwl", r"Frequency-aware \emph{(published)}"),
    ("awwl_eq7", r"\quad as Eq.~(1) is written"),
    ("awwl_normalized", r"\quad normalised to 1"),
    ("awwl_norm_matched", r"\quad budget held fixed"),
    ("mse_ema", r"MSE + EMA"),
    ("awwl_ema", r"Frequency-aware + EMA"),
    ("awwl_subband", r"Per-subband schedules"),
    ("awwl_multilevel", r"Multi-level (3)"),
    ("awwl_spatial", r"Spatially adaptive"),
    ("awwl_learned", r"Learned weighting"),
    ("awwl_gradnorm", r"GradNorm balancing"),
    ("awwl_lifting", r"Learned basis"),
    ("awwl_full", r"All axes combined"),
]

METRICS: list[tuple[str, str, str]] = [
    ("fid", r"FID $\downarrow$", "{:.2f}"),
    ("is_mean", r"IS $\uparrow$", "{:.3f}"),
    ("kid_tf", r"KID $\downarrow$ ($\times 10^{3}$)", "{:.2f}"),
    ("precision", r"Prec. $\uparrow$", "{:.3f}"),
    ("recall", r"Rec. $\uparrow$", "{:.3f}"),
]

# KID is O(1e-2); printing it raw next to FID wastes a column on leading zeros.
SCALE = {"kid_tf": 1e3, "kid": 1e3}

PREAMBLE = (
    "% Generated by scripts/make_tables.py --- do not edit by hand.\n"
    "% Regenerate after every sweep; the paper reads these directly.\n"
)


def _cell(summary, metric: str, fmt: str, expected_seeds: int) -> str:
    if summary is None:
        return "---"
    scale = SCALE.get(metric, 1.0)
    mean = fmt.format(summary.mean * scale)
    std = fmt.format(summary.std * scale)
    text = f"${mean} \\pm {std}$"
    if summary.n < expected_seeds:
        # Flagged, not hidden: an arm averaged over three seeds must not be
        # read as though it carried the same weight as one averaged over five.
        text += f"\\,\\textsuperscript{{{summary.n}}}"
    return text


def build_main_table(rows, epoch: int, expected_seeds: int) -> str:
    by_metric = {
        metric: {s.group: s for s in summarize_groups(rows, metric=metric)}
        for metric, _, _ in METRICS
    }
    present = [(key, label) for key, label in ROWS if any(key in m for m in by_metric.values())]

    lines = [
        PREAMBLE,
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{CIFAR-10, 200 epochs, epoch " + str(epoch) + r". Mean $\pm$ standard "
        r"deviation over " + str(expected_seeds) + r" seeds; a superscript marks arms with "
        r"fewer. KID is from \texttt{torch-fidelity}; see \S\ref{sec:replication} for why "
        r"the bespoke estimator is not reported.}",
        r"\label{tab:full}",
        r"\begin{tabular}{l" + "r" * len(METRICS) + "}",
        r"\toprule",
        "Objective & " + " & ".join(label for _, label, _ in METRICS) + r" \\",
        r"\midrule",
    ]
    for key, label in present:
        cells = [
            _cell(by_metric[metric].get(key), metric, fmt, expected_seeds)
            for metric, _, fmt in METRICS
        ]
        lines.append(f"{label} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def build_comparison_table(rows, baseline: str, metric: str, label: str) -> str:
    results = compare_to_baseline(rows, metric=metric, baseline=baseline)
    lines = [
        PREAMBLE,
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{Paired-by-seed comparison against " + baseline.upper() + r" on " + label +
        r". $p$ is Holm--Bonferroni corrected across the rows shown. Wilcoxon cannot fall "
        r"below $0.0625$ at five seeds and is a direction check, not a verdict.}",
        r"\label{tab:compare-" + metric.replace("_", "") + "}",
        r"\begin{tabular}{lrrrl}",
        r"\toprule",
        r"Objective & $\Delta$ & $t$ & $p$ (Holm) & Verdict \\",
        r"\midrule",
    ]
    names = dict(ROWS)
    for r in results:
        if r.significant:
            verdict = r"\textbf{better}" if r.better else r"\textbf{worse}"
        else:
            verdict = "n.s."
        lines.append(
            f"{names.get(r.group, r.group)} & ${r.mean_delta:+.3f}$ & ${r.t_stat:.2f}$ & "
            f"${r.p_holm:.4f}$ & {verdict} " + r"\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def build_dreambooth_table(rows, baseline: str) -> str:
    """Both DreamBooth metrics in one table, ordered by the published claim.

    The published table's claim is about *rank on both metrics at once*, so the
    two are shown side by side with each objective's rank: that is the form in
    which the claim can be checked, and a per-metric comparison table hides it.
    """
    summaries = {
        metric: {s.group: s for s in summarize_groups(rows, metric=metric)}
        for metric in ("clip_score", "similarity")
    }
    ranks = {
        metric: {
            s.group: i + 1
            for i, s in enumerate(sorted(by_group.values(), key=lambda s: -s.mean))
        }
        for metric, by_group in summaries.items()
    }
    deltas = {
        metric: {r.group: r for r in compare_to_baseline(rows, metric=metric, baseline=baseline)}
        for metric in ("clip_score", "similarity")
    }

    lines = [
        PREAMBLE,
        r"\begin{table}[t]",
        r"\centering",
        r"\small",
        r"\caption{DreamBooth, five seeds per objective, \num{60} images per run. "
        r"Rank is over the nine objectives on that metric. $\Delta$ is the "
        r"paired-by-seed difference from MSE; $p$ is Holm-corrected within each "
        r"metric. The published claim is that the frequency-aware objective is the "
        r"only method in the top two on both metrics.}",
        r"\label{tab:dreambooth}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r" & \multicolumn{3}{c}{CLIP score $\uparrow$} & "
        r"\multicolumn{3}{c}{Subject similarity $\uparrow$} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r"Objective & Mean & Rank & $p$ & Mean & Rank & $p$ \\",
        r"\midrule",
    ]
    names = dict(ROWS)
    order = sorted(
        summaries["clip_score"],
        key=lambda g: ranks["clip_score"].get(g, 99),
    )
    for group in order:
        cells = []
        for metric in ("clip_score", "similarity"):
            summary = summaries[metric].get(group)
            if summary is None:
                cells += ["---", "---", "---"]
                continue
            comparison = deltas[metric].get(group)
            p_cell = "---" if comparison is None else f"${comparison.p_holm:.3f}$"
            if comparison is not None and comparison.significant:
                p_cell = r"$\mathbf{" + f"{comparison.p_holm:.3f}" + r"}$"
            cells += [f"${summary.mean:.4f}$", str(ranks[metric].get(group, "---")), p_cell]
        lines.append(f"{names.get(group, group)} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ledger", type=Path, default=Path("runs/phase0/results.jsonl"))
    parser.add_argument("--epoch", type=int, default=199)
    parser.add_argument("--baseline", default="mse")
    parser.add_argument("--seeds", type=int, default=5, help="Expected seeds per arm.")
    parser.add_argument("--out", type=Path, default=Path("paper/tables"))
    parser.add_argument(
        "--dreambooth", type=Path, default=None,
        help="DreamBooth ledger; builds tables/dreambooth.tex from it as well.",
    )
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}

    # The two sweeps are independent. A CIFAR-10 ledger that is not ready must
    # not stop the DreamBooth table being built, which is what happened while
    # tier 4 was still running and the DreamBooth sweep had already finished.
    rows: list[dict] = []
    if not args.ledger.exists():
        print(f"no ledger at {args.ledger}")
    else:
        rows = [r for r in load_results(args.ledger, kind="eval") if r.get("epoch") == args.epoch]
        if rows:
            written["full.tex"] = build_main_table(rows, args.epoch, args.seeds)
            written["compare_fid.tex"] = build_comparison_table(rows, args.baseline, "fid", "FID")
            written["compare_is.tex"] = build_comparison_table(
                rows, args.baseline, "is_mean", "Inception Score"
            )
        else:
            print(f"no eval rows at epoch {args.epoch} in {args.ledger}")

    if args.dreambooth and args.dreambooth.exists():
        # DreamBooth rows carry no epoch: a fine-tune has one final model.
        db_rows = list(load_results(args.dreambooth, kind="eval"))
        if db_rows:
            written["dreambooth.tex"] = build_dreambooth_table(db_rows, args.baseline)
        else:
            print(f"no eval rows in {args.dreambooth}")
    elif args.dreambooth:
        print(f"no DreamBooth ledger at {args.dreambooth}")

    if not written:
        print("nothing to write")
        return 1

    for name, body in written.items():
        (args.out / name).write_text(body, encoding="utf-8")
        print(f"wrote {args.out / name}")

    # Only meaningful for the CIFAR-10 sweep, whose ROWS this is. Reporting it
    # when that ledger was absent lists every arm as unrun, which is alarming
    # and false.
    if rows:
        groups = sorted({str(r.get("group")) for r in rows})
        unknown = [g for g in groups if g not in dict(ROWS)]
        if unknown:
            print(f"\nnot in the display order, so omitted from the table: {', '.join(unknown)}")
            print("add them to ROWS in this script to include them")
        missing = [k for k, _ in ROWS if k not in groups]
        if missing:
            print(f"\nstill unrun: {', '.join(missing)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
